### ISSUE TITLE
version mismatch between ROCm stack and TensorFlow binary package

### ISSUE THREAD

**Issue by mmmmming18** [ROCmSoftwarePlatform/hiptensorflow#59]
>>> import tensorflow as tf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/__init__.py", line 72, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/__init__.py", line 61, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 28, in <module>
    _pywrap_tensorflow = swig_import_helper()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow', fp, pathname, description)
ImportError: libhip_hcc.so: cannot open shared object file: No such file or directory

**Comment by whchung** [comment]
@mmmmming18 to help better understand the issue, please help explain your system configuration:

- your hardware configuration
- how did you install ROCm stack
- output of `/opt/rocm/hsa/sample/vector_copy`
- how did you install hiptensorflow

**Comment by mmmmming18** [comment]
@whchung Hi, I re-installed everything in a cleaned system and tensorflow works now. Thank you for your hard work!
