### ISSUE TITLE
 libMIOpen.so missing

### ISSUE THREAD

**Issue by Dekken** [ROCmSoftwarePlatform/hiptensorflow#65]
the library is there, but running mnist/convolution.py fails to find it

```
 python convolutional.py
I tensorflow/stream_executor/dso_loader.cc:139] successfully opened CUDA library libhipblas.so locally
I tensorflow/stream_executor/dso_loader.cc:139] successfully opened CUDA library libhipfft.so locally
I tensorflow/stream_executor/dso_loader.cc:139] successfully opened CUDA library libhip_hcc.so locally
I tensorflow/stream_executor/dso_loader.cc:139] successfully opened CUDA library libhiprng.so locally
I tensorflow/stream_executor/dso_loader.cc:130] Couldn't open CUDA library libMIOpen.so. LD_LIBRARY_PATH:
I tensorflow/stream_executor/cuda/miopen_dnn.cc:3533] Unable to load cuDNN DSO
Extracting data/train-images-idx3-ubyte.gz
Traceback (most recent call last):
  File "convolutional.py", line 339, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "convolutional.py", line 136, in main
    train_data = extract_data(train_data_filename, 60000)
  File "convolutional.py", line 83, in extract_data
    buf = bytestream.read(IMAGE_SIZE * IMAGE_SIZE * num_images * NUM_CHANNELS)
  File "/usr/lib/python2.7/gzip.py", line 268, in read
    self._read(readsize)
  File "/usr/lib/python2.7/gzip.py", line 315, in _read
    self._read_eof()
  File "/usr/lib/python2.7/gzip.py", line 354, in _read_eof
    hex(self.crc)))
IOError: CRC check failed 0x1fb8d027 != 0xea2e57fdL
```

**Comment by sunway513** [comment]
MIOpen library is not configured properly, you can try the following steps to rebuild it from source:
`cd ~ && git clone https://github.com/RadeonOpenCompute/rocm-cmake.git && cd ~/rocm-cmake && mkdir -p build && cd build && cmake .. && cmake --build . --target install
cd ~ && git clone https://github.com/RadeonOpenCompute/clang-ocl.git && cd ~/clang-ocl && mkdir -p build && cd build && cmake .. && cmake --build . --target install
cd ~ && git clone https://github.com/ROCmSoftwarePlatform/MIOpenGEMM.git && cd ~/MIOpenGEMM && mkdir -p build && cd build && cmake .. && cmake --build . --target install
cd ~ && git clone https://github.com/ROCmSoftwarePlatform/MIOpen.git
cd ~/MIOpen && mkdir -p build && cd build && \ 
    CXX=/opt/rocm/hcc/bin/hcc cmake -DMIOPEN_BACKEND=HIP -DCMAKE_PREFIX_PATH="/opt/rocm/hcc;/opt/rocm/hip" -DCMAKE_CXX_FLAGS="-isystem /usr/include/x86_64-linux-gnu/" .. -DMIOPEN_MAKE_BOOST_PUBLIC=ON && \
    make install -j $(nproc)
`

**Comment by Dekken** [comment]
thanks but if fails

**Comment by sunway513** [comment]
what's the failure signature?

**Comment by Dekken** [comment]
I think it's syntactically incorrect.  there's some missing "&&" and a few random extra \\

```
philix@stryk:~$ cd ~ && git clone https://github.com/RadeonOpenCompute/rocm-cmake.git && cd ~/rocm-cmake && mkdir -p build && cd build && cmake .. && cmake --build . --target install cd ~ && git clone https://github.com/RadeonOpenCompute/c lang-ocl.git && cd ~/clang-ocl && mkdir -p build && cd build && cmake .. && cmake --build . --target install cd ~ && git clone https://github.com/ROCmSoftwarePlatform/MIOpenGEMM.git && cd ~/MIOpenGEMM && mkdir -p build && cd build && cmake  .. && cmake --build . --target install cd ~ && git clone https://github.com/ROCmSoftwarePlatform/MIOpen.git cd ~/MIOpen && mkdir -p build && cd build && \ CXX=/opt/rocm/hcc/bin/hcc cmake -DMIOPEN_BACKEND=HIP -DCMAKE_PREFIX_PATH="/opt/rocm /hcc;/opt/rocm/hip" -DCMAKE_CXX_FLAGS="-isystem /usr/include/x86_64-linux-gnu/" .. -DMIOPEN_MAKE_BOOST_PUBLIC=ON && \ make install -j $(nproc)
Cloning into 'rocm-cmake'...
remote: Counting objects: 342, done.
remote: Total 342 (delta 0), reused 0 (delta 0), pack-reused 342
Receiving objects: 100% (342/342), 41.78 KiB | 0 bytes/s, done.
Resolving deltas: 100% (158/158), done.
-- The C compiler identification is GNU 6.3.0
-- The CXX compiler identification is GNU 6.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /home/philix/rocm-cmake/build
Unknown argument cd
Unknown argument /home/philix
Usage: cmake --build <dir> [options] [-- [native-options]]
Options:
  <dir>          = Project binary directory to be built.
  --target <tgt> = Build <tgt> instead of default targets.
                   May only be specified once.
  --config <cfg> = For multi-configuration tools, choose <cfg>.
  --clean-first  = Build target 'clean' first, then build.
                   (To clean only, use --target 'clean'.)
  --use-stderr   = Ignored.  Behavior is default in CMake >= 3.0.
  --             = Pass remaining options to the native tool.
```

**Comment by Dekken** [comment]
resolving this

```
philix@stryk:~$ cd ~ && git clone https://github.com/RadeonOpenCompute/rocm-cmake.git && cd ~/rocm-cmake && mkdir -p build && cd build && cmake .. && cmake --build . --target install && cd ~ && git clone https://github.com/RadeonOpenComput e/clang-ocl.git && cd ~/clang-ocl && mkdir -p build && cd build && cmake .. && cmake --build . --target install && cd ~ && git clone https://github.com/ROCmSoftwarePlatform/MIOpenGEMM.git && cd ~/MIOpenGEMM && mkdir -p build && cd build &&  cmake .. && cmake --build . --target install cd ~ && git clone https://github.com/ROCmSoftwarePlatform/MIOpen.git cd ~/MIOpen && mkdir -p build && cd build && CXX=/opt/rocm/hcc/bin/hcc cmake -DMIOPEN_BACKEND=HIP -DCMAKE_PREFIX_PATH="/opt/ rocm/hcc;/opt/rocm/hip" -DCMAKE_CXX_FLAGS="-isystem /usr/include/x86_64-linux-gnu/" .. -DMIOPEN_MAKE_BOOST_PUBLIC=ON && make install -j $(nproc)
Cloning into 'rocm-cmake'...
remote: Counting objects: 342, done.
remote: Total 342 (delta 0), reused 0 (delta 0), pack-reused 342
Receiving objects: 100% (342/342), 41.78 KiB | 0 bytes/s, done.
Resolving deltas: 100% (158/158), done.
-- The C compiler identification is GNU 6.3.0
-- The CXX compiler identification is GNU 6.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /home/philix/rocm-cmake/build
Install the project...
-- Install configuration: ""
-- Up-to-date: /opt/rocm/./share
CMake Error at cmake_install.cmake:36 (file):
  file INSTALL cannot set permissions on "/opt/rocm/./share"


Makefile:83: recipe for target 'install' failed
make: *** [install] Error 1
```

this is the output

**Comment by sunway513** [comment]
Plz try my original posted steps again (I've cleaned it a bit), thanks.

**Comment by Dekken** [comment]
Excellent thank you - this has fixed it.

**Comment by sunway513** [comment]
Thanks, great news :-)
