### ISSUE TITLE
Windows linux subsystem with hip tensorflow

### ISSUE THREAD

**Issue by zhhhaolong** [ROCmSoftwarePlatform/hiptensorflow#70]
I am using the ubuntu subsystem on windows to try to get hip tensorflow to work. I followed the basic installation guide and installed hip tensorflow. 

However, after everything is installed, I started python (2.7.12) do 
import tensorflow as tf

The following error pops up:

>>[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
 import tensorflow as tf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/__init__.py", line 72, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/__init__.py", line 61, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 28, in <module>
    _pywrap_tensorflow = swig_import_helper()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow', fp, pathname, description)
ImportError: /usr/local/lib/python2.7/dist-packages/tensorflow/python/_pywrap_tensorflow.so: cannot enable executable stack as shared object requires: Invalid argument
Failed to load the native TensorFlow runtime.
See https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/get_started/os_setup.md#import_error

I am not sure what is  wrong here. Any help/suggestion is welcomed.

**Comment by whchung** [comment]
windows, and ubuntu on windows is not supported. Please install native ROCm stack at: https://github.com/RadeonOpenCompute/ROCm
